server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

zuul:
  routes:
    whikies:
      path: /**
      url: http://localhost:8090

ribbon:
  eureka:
    enabled: false

logging:
  level:
    org.springframework.security: DEBUG