server:
  port: 8080
#security:
#  ignored:
#  - "/**.js"
  #- "/**"
  #- "*.bundle.*"
  # should be /static ?

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

logging:
  level:
    org.springframework.security: DEBUG