server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /
      suffix: .html

zuul:
  routes:
    whikies:
      path: /api/whiskies/**
      url: http://localhost:8090/v1/whiskies

ribbon:
  eureka:
    enabled: false

logging:
  level:
    #root: DEBUG
    org.springframework.security: DEBUG